# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/infra/database/schema.rs"

[migrations_directory]
dir = "src/infra/database/migrations"
