name: pre deploy frontend
run-name: Check tests and lint 🚀
on: 
  push:
    paths-ignore:
      - 'src-tauri/**'
jobs:
  pre-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      - name: Install dependencies
        run: pnpm install

      - name: Check lint
        run: pnpm run lint

      - name: Check tests
        run: pnpm test